language: node_js
node_js: '10'

cache:
  directories:
    - node_modules

before_script:
  - npm test

deploy:
  provider: heroku
  api_key:
    secure: $HEROKU_API_KEY
  app:
    master: bg-nrp-alp-pz
  run: restart

branches:
  only:
    - develop
    - master
